### ISSUE TITLE
Boilerplate Demo

### ISSUE THREAD

**Issue by cortezcristian** [TestArmada/magellan-seleniumgrid-executor#2]
Is there a `magellan-seleniumgrid-executor` bolierplate? or demo?

**Comment by archlichking** [comment]
@cortezcristian We don't have boilerplate for this executor unfortunately. But you can follow this command example https://github.com/TestArmada/magellan-seleniumgrid-executor#example. 

I am able to use https://github.com/SeleniumHQ/docker-selenium to create local selenium grid and run test with chrome on it with the command.
